/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import masproject.Agents.DataProcessor;
import masproject.Agents.Message;
import masproject.Agents.MetaAgent;
import masproject.Agents.Portal;
import masproject.Agents.Router;
import masproject.Agents.SocketAgent;
import masproject.Agents.UserAgent;

/**
 *
 * @author n3148087
 */
public class MASGui extends javax.swing.JFrame
{

    /**
     * Creates new form MASGui
     */
    private final Map<String, Portal> portalMap;
    private Router router;

    /**
     *
     */
    public MASGui()
    {
        portalMap = new HashMap<>();
        DataProcessor dp;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        routerButton = new javax.swing.JButton();
        portalButton = new javax.swing.JButton();
        agentButton = new javax.swing.JButton();
        sendButton = new javax.swing.JButton();
        routerField = new javax.swing.JTextField();
        portalField = new javax.swing.JTextField();
        agentField = new javax.swing.JTextField();
        fromField = new javax.swing.JTextField();
        toField = new javax.swing.JTextField();
        sendField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputBox = new javax.swing.JTextArea();
        portalForAgentField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textArea1 = new java.awt.TextArea();
        jTextField1 = new javax.swing.JTextField();
        JTextField2 = new javax.swing.JScrollPane();
        jTextField2 = new javax.swing.JTextArea();
        MeshBox = new javax.swing.JCheckBox();
        routerPortalField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        networkTest = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        filepath = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        classname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        routerButton.setText("add router");
        routerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routerButtonActionPerformed(evt);
            }
        });

        portalButton.setText("add portal");
        portalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portalButtonActionPerformed(evt);
            }
        });

        agentButton.setText("add agent");
        agentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentButtonActionPerformed(evt);
            }
        });

        sendButton.setText("send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        routerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routerFieldActionPerformed(evt);
            }
        });

        portalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portalFieldActionPerformed(evt);
            }
        });

        agentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentFieldActionPerformed(evt);
            }
        });

        fromField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("from");

        jLabel3.setText("to");

        jLabel4.setText("message");

        outputBox.setEditable(false);
        outputBox.setColumns(20);
        outputBox.setRows(5);
        jScrollPane1.setViewportView(outputBox);

        portalForAgentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portalForAgentFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Router Name");

        jLabel6.setText("Portal name");

        jLabel7.setText("Agent Name");

        jLabel8.setText("Portal to assign to");

        jTextField1.setText("jTextField1");

        jTextField2.setColumns(20);
        jTextField2.setRows(5);
        JTextField2.setViewportView(jTextField2);

        MeshBox.setText("Mesh");
        MeshBox.setActionCommand("MeshCheckbox");
        MeshBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeshBoxActionPerformed(evt);
            }
        });

        routerPortalField.setText("localhost");
        routerPortalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routerPortalFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("RouterAddress");

        networkTest.setText("System test(warning: intensive)");
        networkTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkTestActionPerformed(evt);
            }
        });

        jLabel10.setText("filepath");

        filepath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filepathActionPerformed(evt);
            }
        });

        jLabel11.setText("classname");

        jLabel12.setText("reflection options:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sendButton)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fromField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(toField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(sendField, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(networkTest))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(agentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(portalButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(routerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(routerField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(portalField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(agentField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(portalForAgentField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(filepath))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(MeshBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(routerPortalField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                                .addComponent(jLabel12)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(classname, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(routerButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(routerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portalButton)
                    .addComponent(portalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(MeshBox)
                    .addComponent(routerPortalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agentButton)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(agentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(portalForAgentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(filepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(classname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(networkTest)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendButton)
                    .addComponent(fromField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void portalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portalFieldActionPerformed

    }//GEN-LAST:event_portalFieldActionPerformed

    private void routerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routerFieldActionPerformed

    }//GEN-LAST:event_routerFieldActionPerformed

    private void agentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agentFieldActionPerformed

    private void routerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routerButtonActionPerformed
        router = new Router(routerField.getText());
        router.start();
    }//GEN-LAST:event_routerButtonActionPerformed
    /**
     * generates new agent and attaches it to a portal
     *
     * @param evt
     */
    private void agentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentButtonActionPerformed
        UserAgent newAgent = null;
        if(filepath.getText().isEmpty()&&classname.getText().isEmpty())
        {
          newAgent = new UserAgent(
                agentField.getText(), null, portalMap.get(portalForAgentField.getText())
                 
        );
          newAgent.setProc(new GuiProcessor(newAgent, this));
        }
        else
        {
            try {
                URL classurl=new URL("file://"+filepath.getText().replace("\\", "/"));
                URL [] urls=new URL[]{classurl};
                URLClassLoader loader = new URLClassLoader(urls);
             Class c=   loader.loadClass(classname.getText());
             Constructor cc=c.getConstructor(String.class,Portal.class);
          newAgent=(UserAgent) cc.newInstance(agentField.getText(), portalMap.get(portalForAgentField.getText()));
            } catch (MalformedURLException | ClassNotFoundException | NoSuchMethodException | SecurityException | InstantiationException | IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
                Logger.getLogger(MASGui.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        
        }
      
        
        newAgent.start();
        pollPortals();
    }//GEN-LAST:event_agentButtonActionPerformed

    private void fromFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromFieldActionPerformed
    /**
     * sends message from agent to another agent
     *
     * @param evt
     */
    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        Message msg = new Message();
        msg.setMsg(this.sendField.getText());
        msg.setSender(this.fromField.getText());
        msg.setReceiver(this.toField.getText());
        for (Map.Entry<String, Portal> e : portalMap.entrySet())
        {
            if (e.getValue().getLocalAgent(msg.getSender()) != null)
            {
                e.getValue().getLocalAgent(msg.getSender()).sendMessage(msg);
                break;
            }

        }
        pollPortals();
    }//GEN-LAST:event_sendButtonActionPerformed

    private void portalForAgentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portalForAgentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portalForAgentFieldActionPerformed

    /**
     * generates new portal
     *
     * @param evt
     */
    private void portalButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_portalButtonActionPerformed
    {//GEN-HEADEREND:event_portalButtonActionPerformed

        Portal newPortal = new Portal(portalField.getText());
        SocketAgent agent = new SocketAgent("socket", routerPortalField.getText(), newPortal);
        newPortal.setSocketAgent(agent);
        portalMap.put(newPortal.getName(), newPortal);

        //insert new portal into all other portals
        //maps and all other portals into the new portals map
        //starts portals thread
        //refreshes the portal listing
        if (MeshBox.isSelected())
        {
            for (Map.Entry<String, Portal> e : portalMap.entrySet())
            {
                newPortal.addPortal(e.getValue());
                e.getValue().addPortal(newPortal);

            }

        }

        newPortal.start();
        agent.start();
        pollPortals();
        //}
    }//GEN-LAST:event_portalButtonActionPerformed

    private void MeshBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeshBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MeshBoxActionPerformed

    private void routerPortalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routerPortalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routerPortalFieldActionPerformed

    //network stress test single vm causes interleving in the gui text box
    private void networkTestActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_networkTestActionPerformed
    {//GEN-HEADEREND:event_networkTestActionPerformed
        if(router==null)
        {
        router = new Router("r1");
        }
        
        portalMap.clear(); // clear the portal map
        for (int i = 0; i < 15; i++) 
        {
            Portal p = new Portal("portal" + i);
            portalMap.put(p.getName(), p);
            SocketAgent agent = new SocketAgent("Socket", "localhost", p);
            p.setSocketAgent(agent);
            agent.start();
            p.start();
            for (int x = 0; x < 15; x++)
            {
                UserAgent a = new UserAgent("agent" + p.getName() + x, null, p);
                a.setProc(new GuiProcessor(agent, this));
                a.start();

            }
        }
        pollPortals();
        //dont want to lock the gui
        Thread thread = new Thread(new Runnable()
        {

            @Override
            public void run()
            {

                for (Portal p : portalMap.values())
                {
                    for (MetaAgent x : p.getInternalRoutingTable().values())
                    {
                        Random r = new Random();
                        for (int y = 0; y < 2; y++)
                        {

                            x.sendMessage(new Message(x.getName(), "oh hi mark", "agent" + "portal" + r.nextInt(14) + r.nextInt(14)));

                        }

                    }
                }

            }

        });

        thread.start();
    }//GEN-LAST:event_networkTestActionPerformed

    private void filepathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filepathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filepathActionPerformed

    /**
     * lists the all the known portals and their agents hierarchy
     */
    private void pollPortals()
    {
        jTextField2.setText("Router: \n");
        {if(router!=null)
        {
         jTextField2.setText(jTextField2.getText()+router.getName()+"\n");
        }
            }
        jTextField2.setText(jTextField2.getText()+"Portals: \n");
        for (Map.Entry e : portalMap.entrySet())
        {

            jTextField2.setText(jTextField2.getText() + e.getKey() + "\n");
            jTextField2.setText(jTextField2.getText() + "   " + "agents:" + "\n");
            for (Map.Entry ep : ((Portal) e.getValue()).getInternalRoutingTable().entrySet())
            {
                jTextField2.setText(jTextField2.getText() + "        " + ep.getKey() + "\n");
            }

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MASGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MASGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MASGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MASGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MASGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JTextField2;
    private javax.swing.JCheckBox MeshBox;
    private javax.swing.JButton agentButton;
    private javax.swing.JTextField agentField;
    private javax.swing.JTextField classname;
    private javax.swing.JTextField filepath;
    private javax.swing.JTextField fromField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea jTextField2;
    private javax.swing.JButton networkTest;
    public javax.swing.JTextArea outputBox;
    private javax.swing.JButton portalButton;
    private javax.swing.JTextField portalField;
    private javax.swing.JTextField portalForAgentField;
    private javax.swing.JButton routerButton;
    private javax.swing.JTextField routerField;
    private javax.swing.JTextField routerPortalField;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextField sendField;
    private java.awt.TextArea textArea1;
    private javax.swing.JTextField toField;
    // End of variables declaration//GEN-END:variables
}
